<a href="https://colab.research.google.com/github/Karthiharaj/python_fundamental/blob/main/Embedding_examples_updated.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**BAG OF WORDS**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
# Sample text
documents = [
    "I love programming",
    "Python is great for data science",
    "I love Python"
]

In [ ]:
# Initialize CountVectorizer
vectorizer = CountVectorizer()

In [ ]:
# Fit and transform the documents
X = vectorizer.fit_transform(documents)

In [ ]:
# Display the BoW representation
print(vectorizer.get_feature_names_out())
print(X.toarray())

['data' 'for' 'great' 'is' 'love' 'programming' 'python' 'science']
[[0 0 0 0 1 1 0 0]
 [1 1 1 1 0 0 1 1]
 [0 0 0 0 1 0 1 0]]


**TF_IDF Vectorizer**

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
# Sample text
documents = [
    "I love python programming",
    "Python is great for data science",
    "I love Python",
    "Python is one of my favorite language"
]

In [ ]:
# Initialize TfidfVectorizer
vectorizer = TfidfVectorizer()

In [ ]:
# Fit and transform the documents
X = vectorizer.fit_transform(documents)

In [ ]:
# Display the TF-IDF representation
print(vectorizer.get_feature_names_out())
print(X.toarray())


['data' 'favorite' 'for' 'great' 'is' 'language' 'love' 'my' 'of' 'one'
 'programming' 'python' 'science']
[[0.         0.         0.         0.         0.         0.
  0.5728925  0.         0.         0.         0.72664149 0.37919167
  0.        ]
 [0.45203489 0.         0.45203489 0.45203489 0.3563895  0.
  0.         0.         0.         0.         0.         0.23589056
  0.45203489]
 [0.         0.         0.         0.         0.         0.
  0.83388421 0.         0.         0.         0.         0.55193942
  0.        ]
 [0.         0.41190608 0.         0.         0.32475149 0.41190608
  0.         0.41190608 0.41190608 0.41190608 0.         0.21494968
  0.        ]]


**TF(t,d)=
Number of times term t appears in document d  / Total number of terms in document d **


If the word "data" appears 3 times in a document of 100 words, the term frequency is:

𝑇
𝐹
(
"data"
,
𝑑
)
=
3 /
100
=
0.03



**IDF(t,D)=log( Total number of documents in the corpus  /   Number of documents containing the term t + 1
​
 )

If "data" appears in 50 out of 100 documents, then:

𝐼
𝐷
𝐹
(
"data"
,
𝐷
)
=
log
⁡
(
100 /
50
)
=
log
⁡
(
2
)
≈
0.3010
IDF("data",D)=log(
50
100
​
 )=log(2)≈0.3010

TF("data", d) = 0.03
IDF("data", D) ≈ 0.3010
So:

𝑇
𝐹
−
𝐼
𝐷
𝐹
(
"data"
,
𝑑
,
𝐷
)
=
0.03
×
0.3010
≈
0.00903

TF−IDF("data",d,D)=0.03×0.3010≈0.00903

**Why TF-IDF is Useful:
Frequency (TF) captures the importance of the word within a document.
Inverse Frequency (IDF) reduces the weight of words that are common across many documents, so it emphasizes terms that are more unique and potentially more meaningful.**

In [ ]:
import pandas as pd
import numpy as np

In [7]:
corpus = [
    "I love python programming",
    "Python is great for data science",
    "I love Python",
    "Python is one of my favorite language"
]



In [3]:
words_set = set()

for doc in  corpus:
    words = doc.split(' ')
    words_set = words_set.union(set(words))
print(words)
print('Number of words in the corpus:',len(words_set))
print('The words in the corpus: \n', words_set)

['Python', 'is', 'one', 'of', 'my', 'favorite', 'language']
Number of words in the corpus: 15
The words in the corpus: 
 {'I', 'Python', 'one', 'is', 'for', 'great', 'favorite', 'of', 'my', 'love', 'data', 'language', 'programming', 'science', 'python'}


In [4]:
n_docs = len(corpus)         #·Number of documents in the corpus
n_words_set = len(words_set) #·Number of unique words in the

print("the no of documentys is ", n_docs)
print(n_words_set)

the no of documentys is  4
15


In [ ]:
df_tf = pd.DataFrame(np.zeros((n_docs, n_words_set)), columns=['I', 'Python', 'of', 'science', 'my', 'data', 'great', 'is', 'one', 'love', 'programming', 'python', 'language', 'favorite', 'for'])
df_tf

I  Python   of  science   my  data  great   is  one  love  programming  \
0  0.0     0.0  0.0      0.0  0.0   0.0    0.0  0.0  0.0   0.0          0.0   
1  0.0     0.0  0.0      0.0  0.0   0.0    0.0  0.0  0.0   0.0          0.0   
2  0.0     0.0  0.0      0.0  0.0   0.0    0.0  0.0  0.0   0.0          0.0   
3  0.0     0.0  0.0      0.0  0.0   0.0    0.0  0.0  0.0   0.0          0.0   

   python  language  favorite  for  
0     0.0       0.0       0.0  0.0  
1     0.0       0.0       0.0  0.0  
2     0.0       0.0       0.0  0.0  
3     0.0       0.0       0.0  0.0

In [ ]:

#Compute Term Frequency (TF)
for i in range(n_docs):
    words = corpus[i].split(' ') # Words in the document
    for w in words:
        df_tf[w][i] = df_tf[w][i] + (1 / len(words))

df_tf

<ipython-input-39-3c08f8f0724f>:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_tf[w][i] = df_tf[w][i] + (1 / len(words))


I    Python        of   science        my      data     great  \
0  0.250000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
1  0.000000  0.166667  0.000000  0.166667  0.000000  0.166667  0.166667   
2  0.333333  0.333333  0.000000  0.000000  0.000000  0.000000  0.000000   
3  0.000000  0.142857  0.142857  0.000000  0.142857  0.000000  0.000000   

         is       one      love  programming  python  language  favorite  \
0  0.000000  0.000000  0.250000         0.25    0.25  0.000000  0.000000   
1  0.166667  0.000000  0.000000         0.00    0.00  0.000000  0.000000   
2  0.000000  0.000000  0.333333         0.00    0.00  0.000000  0.000000   
3  0.142857  0.142857  0.000000         0.00    0.00  0.142857  0.142857   

        for  
0  0.000000  
1  0.166667  
2  0.000000  
3  0.000000

In [ ]:
print("IDF of: ")

idf = {}

for w in words_set:
    k = 1    # number of documents in the corpus that contain this word

    for i in range(n_docs):
        if w in corpus[i].split():
            k += 1

    idf[w] =  np.log10(n_docs / k)

    print(f'{w:>15}: {idf[w]:>10}' )

IDF of: 
              I: 0.12493873660829992
         Python:        0.0
             of: 0.3010299956639812
        science: 0.3010299956639812
             my: 0.3010299956639812
           data: 0.3010299956639812
          great: 0.3010299956639812
             is: 0.12493873660829992
            one: 0.3010299956639812
           love: 0.12493873660829992
    programming: 0.3010299956639812
         python: 0.3010299956639812
       language: 0.3010299956639812
       favorite: 0.3010299956639812
            for: 0.3010299956639812


In [ ]:
df_tf_idf = df_tf.copy()

for w in words_set:
    for i in range(n_docs):
        df_tf_idf[w][i] = df_tf[w][i] * idf[w]

df_tf_idf

<ipython-input-41-393ab078b638>:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_tf_idf[w][i] = df_tf[w][i] * idf[w]


I  Python        of   science        my      data     great  \
0  0.031235     0.0  0.000000  0.000000  0.000000  0.000000  0.000000   
1  0.000000     0.0  0.000000  0.050172  0.000000  0.050172  0.050172   
2  0.041646     0.0  0.000000  0.000000  0.000000  0.000000  0.000000   
3  0.000000     0.0  0.043004  0.000000  0.043004  0.000000  0.000000   

         is       one      love  programming    python  language  favorite  \
0  0.000000  0.000000  0.031235     0.075257  0.075257  0.000000  0.000000   
1  0.020823  0.000000  0.000000     0.000000  0.000000  0.000000  0.000000   
2  0.000000  0.000000  0.041646     0.000000  0.000000  0.000000  0.000000   
3  0.017848  0.043004  0.000000     0.000000  0.000000  0.043004  0.043004   

        for  
0  0.000000  
1  0.050172  
2  0.000000  
3  0.000000

In [14]:
import pandas as pd
import numpy as np

expl1=["i like to have coffee",
       "what do you like to have coffee ?",
       "what is your name ?",
       "if you are able to travel",
       "how many times you drink coffee"]

words_set = set()

for doc in  expl1:
    words = doc.split(' ')
    words_set = words_set.union(set(words))
print('Number of words in the corpus:',len(words_set))
print('The words in the corpus: \n', words_set)

n_docs = len(expl1)         #·Number of documents in the corpus
n_words_set = len(words_set) #·Number of unique words in the

print("the no of documentys is ", n_docs)
print(n_words_set)

df_tf = pd.DataFrame(np.zeros((n_docs, n_words_set)), columns=['many', 'if', 'is', 'able', 'to', 'what', 'times', 'like', 'name', 'coffee', 'i', 'drink', 'you', '?', 'how', 'your', 'travel', 'do', 'are', 'have'
])
df_tf




#Compute Term Frequency (TF)
for i in range(n_docs):
    words = expl1[i].split(' ') # Words in the document
    for w in words:
        df_tf[w][i] = df_tf[w][i] + (1 / len(words))

df_tf

Number of words in the corpus: 20
The words in the corpus: 
 {'many', 'if', 'is', 'able', 'to', 'what', 'times', 'like', 'name', 'coffee', 'i', 'drink', 'you', '?', 'how', 'your', 'travel', 'do', 'are', 'have'}
the no of documentys is  5
20


<ipython-input-14-b3d741aa920b>:35: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_tf[w][i] = df_tf[w][i] + (1 / len(words))


many        if   is      able        to   what     times   like  name  \
0  0.000000  0.000000  0.0  0.000000  0.200000  0.000  0.000000  0.200   0.0   
1  0.000000  0.000000  0.0  0.000000  0.125000  0.125  0.000000  0.125   0.0   
2  0.000000  0.000000  0.2  0.000000  0.000000  0.200  0.000000  0.000   0.2   
3  0.000000  0.166667  0.0  0.166667  0.166667  0.000  0.000000  0.000   0.0   
4  0.166667  0.000000  0.0  0.000000  0.000000  0.000  0.166667  0.000   0.0   

     coffee    i     drink       you      ?       how  your    travel     do  \
0  0.200000  0.2  0.000000  0.000000  0.000  0.000000   0.0  0.000000  0.000   
1  0.125000  0.0  0.000000  0.125000  0.125  0.000000   0.0  0.000000  0.125   
2  0.000000  0.0  0.000000  0.000000  0.200  0.000000   0.2  0.000000  0.000   
3  0.000000  0.0  0.000000  0.166667  0.000  0.000000   0.0  0.166667  0.000   
4  0.166667  0.0  0.166667  0.166667  0.000  0.166667   0.0  0.000000  0.000   

        are   have  
0  0.000000  0.200  
1  0.000000  0.125  
2  0.000000  0.000  
3  0.166667  0.000  
4  0.000000  0.000

# Bag of words
# TF-IDF
#Word2vec
#GLOVE
#Transformer